package main

import (
	//"strings"
	//"fmt"
	"regexp"
	"fmt"
)

func main() {
	expDropTable  := regexp.MustCompile("(?i)^DROP\\sTABLE\\s.*?`{0,1}(.*?)`{0,1}\\.{0,1}`{0,1}([^`\\.]+?)`{0,1}\\s.*")

	str := "DROP TABLE `dt_varchar` /* generated by server */"
	//if str[:10] == "DROP TABLE" {
	//	ts1 := strings.Index(str, "`")
	//	ts2 := strings.Index(str[ts1+1:], "`")
	//	fmt.Println(ts1, ts2, str[ts1+1:])
	//	table := str[ts1+1:ts1+ts2+1]
	//	fmt.Println(table)
	//}
	m := expDropTable.FindSubmatch([]byte(str))
	fmt.Println(m)
	for _, v := range m{
		fmt.Println(string(v))
	}

}
